collections:
  - name: ansible.posix
  - name: community.general
  - name: community.hashi_vault
  - name: infoblox.nios_modules
  - name: dellemc.powerstore
  - name: netbox.netbox
  - name: community.vmware
